;; generated by ffi/gen/genffi for ffi/libc

(includes "string.h" "stdio.h" "stdlib.h" )
(sig strlen ((* char) -> ulong))
(sig strerror (int -> (* char)))
(sig system ((* char) -> int))
(sig getenv ((* char) -> (* char)))
(sig abort ( -> void))
(sig tmpnam ((* char) -> (* char)))
(sig memcpy ((* void) (* void) ulong -> (* void)))
(sig realloc ((* void) ulong -> (* void)))
