(include "lib/core.scm")
(include "lib/string.scm")
(include "lib/io.scm")

(print-string "opening ") (printn (sys:argv 1))
(let ((fd (open (sys:argv 1) 0 0))
      (buffer (make-string 100)))
  (printn (read fd 100))
  (printn (read-into-buffer fd buffer))
  )
(printn "tests/out.txt\x00")
(let ((fd (open "tests/out.txt\x00" #x202 #o777)))
  (printn (write fd "this is a test\n"))
  (close fd)
  )
