(define (lex)
  (let ((state 0))
    (define (step ch)
      (if (%eq? state 0)
	  (if (or (and (%le? ch 57) (%ge? ch 48)))
	      (set! state 14)
	      (if (or (%eq? ch 39))
		  (set! state 11)
		  (if (or (%eq? ch 35))
		      (set! state 4)
		      (if (or (%eq? ch 34))
			  (set! state 7)
			  (if (or (%eq? ch 10))
			      (set! state 3)
			      (if (or (%eq? ch 9) (%eq? ch 32))
				  (set! state 2)
				  (if (or (and (%le? ch 90) (%ge? ch 65)) (%eq? ch 95) (and (%le? ch 122) (%ge? ch 97)))
				      (set! state 15)
				      (if (or (%eq? ch 37) (and (%le? ch 41) (%ge? ch 40)) (and (%le? ch 46) (%ge? ch 43)) (%eq? ch 58) (and (%le? ch 62) (%ge? ch 60)) (%eq? ch 91) (%eq? ch 93) (%eq? ch 123) (%eq? ch 125))
					  (set! state 10)
					  (set! state 1)
					  ))))))))
	  (if (%eq? state 1)
	      (set! state 1)

	      (if (%eq? state 2)
		  (if (or (%eq? ch 35))
		      (set! state 4)
		      (if (or (%eq? ch 10))
			  (set! state 3)
			  (if (or (%eq? ch 9) (%eq? ch 32))
			      (set! state 2)
			      (set! state 1)
			      )))
		  (if (%eq? state 3)
		      (if (or (and (%le? ch 10) (%ge? ch 9)) (%eq? ch 32))
			  (set! state 3)
			  (set! state 1)
			  )
		      (if (%eq? state 4)
			  (if (or (%eq? ch 10))
			      (set! state 6)
			      (set! state 5)
			      )
			  (if (%eq? state 5)
			      (if (or (%eq? ch 10))
				  (set! state 6)
				  (set! state 5)
				  )
			      (if (%eq? state 6)
				  (set! state 1)

				  (if (%eq? state 7)
				      (if (or (%eq? ch 34))
					  (set! state 9)
					  (set! state 8)
					  )
				      (if (%eq? state 8)
					  (if (or (%eq? ch 34))
					      (set! state 9)
					      (set! state 8)
					      )
					  (if (%eq? state 9)
					      (set! state 1)

					      (if (%eq? state 10)
						  (set! state 1)

						  (if (%eq? state 11)
						      (if (or (%eq? ch 39))
							  (set! state 13)
							  (set! state 12)
							  )
						      (if (%eq? state 12)
							  (if (or (%eq? ch 39))
							      (set! state 13)
							      (set! state 12)
							      )
							  (if (%eq? state 13)
							      (set! state 1)

							      (if (%eq? state 14)
								  (if (or (and (%le? ch 57) (%ge? ch 48)))
								      (set! state 14)
								      (set! state 1)
								      )
								  (if (%eq? state 15)
								      (if (or (and (%le? ch 57) (%ge? ch 48)) (and (%le? ch 90) (%ge? ch 65)) (%eq? ch 95) (and (%le? ch 122) (%ge? ch 97)))
									  (set! state 16)
									  (set! state 1)
									  )
								      (if (%eq? state 16)
									  (if (or (and (%le? ch 57) (%ge? ch 48)) (and (%le? ch 90) (%ge? ch 65)) (%eq? ch 95) (and (%le? ch 122) (%ge? ch 97)))
									      (set! state 16)
									      (set! state 1)
									      )))))))))))))))))))
    (step 49)
    (%printn state)
    (step 50)
    (%printn state)
    (step 51)
    (%printn state)
    (step 32)
    (%printn state)
    (set! state 0)
    (step 97)
    (%printn state)
    (step 98)
    (%printn state)
    (step 99)
    (%printn state)
))
(lex)
